[profile.default]
src = "src"
out = "out"
libs = ["lib"]
solc_version = "0.8.19"
fs_permissions = [{ access = "read", path = "./script/deployParameters/" }]

# See more config options https://github.com/foundry-rs/foundry/tree/master/config
